removes possibility of subbing and unsubbing other users
nerdland-unofficial-fans/nerdlandbot pull request #102
Opened 2021-01-21 19:43 UTC by bobvdvleuten

Small alteration to code so that it prevents unwanted sub and unsub usage where users would provide a discord ID and make the command take effect on other users.

2021-01-21 20:21 UTC, Eva774 submitted a review, later dismissed

2021-01-21 20:43 UTC, Autom3 reviewed
I'd actually prefer to see this without the is_reaction. Reason being is that you'd be putting "business logic" inside your commands.
Ideally you should create a separate function which does everything that's currently inside the subscribe command function.
Then the subscribe function can pass `ctx.author.id` directly into that function as the user_id, and the function that handles clicking the reaction can pass the right user_id into that function as well.

(edit: same for unsubscribe of course)

2021-01-21 20:47 UTC, bobvdvleuten commented
> I'd actually prefer to see this without the is_reaction. Reason being is that you'd be putting "business logic" inside your commands.
> Ideally you should create a separate function which does everything that's currently inside the subscribe command function.
> Then the subscribe function can pass `ctx.author.id` directly into that function as the user_id, and the function that handles clicking the reaction can pass the right user_id into that function as well.
> 
> (edit: same for unsubscribe of course)

Good suggestion, will try that way.

2021-01-23 13:42 UTC, bobvdvleuten commented
@Autom3 have implemented your suggestion and tested

2021-01-24 02:00 UTC, Autom3 requested changes
Code looks great, a few tiny formatting things and one confusing character and I'll approve!

2021-01-24 02:00 UTC, Autom3 commented on nerdlandbot/commands/notify.py
> +                        await self.act_subscribe(ctx, list_name,user.id,)
I suppose this trailing comma is not intended to be here? I know it's a minor thing, but in the future it will be very unclear why that was put there.

2021-01-24 02:00 UTC, Autom3 commented on nerdlandbot/commands/notify.py
> +    async def act_subscribe(self,ctx: commands.Context,list_name: str,user_id: int):
Some minor formatting mistakes, maybe they can be addressed while you're resolving the other comment? :)

2021-01-24 02:00 UTC, Autom3 commented on nerdlandbot/commands/notify.py
> +    async def act_unsubscribe(self,ctx: commands.Context, list_name: str, user_id: int):
One more missing space

2021-01-24 08:36 UTC, bobvdvleuten commented
> 
> 
> Code looks great, a few tiny formatting things and one confusing character and I'll approve!

well spotted, will fix

2021-01-24 13:19 UTC, Autom3 approved these changes

2021-01-24 14:56 UTC, Eva774 approved these changes

2021-01-24 14:57 UTC, merged