Feature/76 youtube
nerdland-unofficial-fans/nerdlandbot pull request #78
Opened 2020-11-14 18:26 UTC by DrSkunk

Adds youtube notification capabilities.

Adds the following commands
- `add_youtube <YouTube channel ID> <text channel ID or name>`
- `remove_youtube <YouTube channel ID>`
- `list_youtube`

2020-11-14 19:12 UTC, bobvdvleuten commented on Commands/youtube.py
> +        Add a Youtube channel to be notified
nitpicking here: doc says add when function is remove ;)

2020-11-14 19:16 UTC, bobvdvleuten commented on Commands/youtube.py
> +            msg = f"Removed notifier for `{youtube_channel_id}`"
Ideally should be translated as well, no?

2020-11-14 19:16 UTC, bobvdvleuten commented on Commands/youtube.py
> +            msg = f"There is no notifier for `{youtube_channel_id}`"
same comment as 89

2020-11-14 19:16 UTC, bobvdvleuten commented on Commands/youtube.py
> +                + f"\n - Channel `channel_id` posts in <#{channel_data['text_channel_id']}>, last video ID: `{channel_data['latest_video_id']}`"
Same comment as 89

2020-11-16 14:22 UTC, ThunderbirdOne requested changes
Looks good aside from some textual changes.

When completed, don't forget to complete YOUTUBE TOKEN in .env file!

2020-11-16 14:22 UTC, ThunderbirdOne commented on Translations/Translations.csv
> +"youtube_added","Added a notifier for `{0}` to be posted in text channel {1}","Notificaties werden toegevoegd voor `{0}` in het #{1} kanaal"
Spoorwegteken voor het engelse kanaal? Ofwel in NL weghalen :D

2020-11-16 14:34 UTC, ThunderbirdOne approved these changes
🚢

2020-11-16 15:50 UTC, bobvdvleuten commented on Commands/youtube.py
> +            raise Exception("Invalid text channel provided")
This will leave a "da kennek nie foump" generic error message in Discord, no, if only handled by an Exception?

2020-11-16 15:51 UTC, bobvdvleuten approved these changes
Had one minor comment but since there's a TODO with it and the functionality is admin only, i think we can go ahead with this.

2020-11-16 17:54 UTC, merged