fix notify length issue
nerdland-unofficial-fans/nerdlandbot pull request #95
Opened 2021-01-17 18:58 UTC by bobvdvleuten

quick fix to split the notify list of users into multiple messages when necessary

2021-01-17 19:04 UTC, Jan-PieterBaert reviewed
Looks good

2021-01-17 19:08 UTC, Autom3 requested changes
Each message will always end with a comma using this implementation. It should look a bit more polished if that's not the case

2021-01-17 19:09 UTC, bobvdvleuten commented
> 
> 
> Each message will always end with a comma using this implementation. It should look a bit more polished if that's not the case

indeed but it's a quick patch for now. Long term should be fixe dindeed

2021-01-17 19:11 UTC, Autom3 approved these changes, later dismissed

2021-01-17 19:54 UTC, Eva774 requested changes

2021-01-17 19:54 UTC, Eva774 commented on Helpers/constants.py
> +DISCORD_MAX_MSG_LENGTH = 2048
The maximum message length is 2000 characters and not 2048.

2021-01-17 19:59 UTC, Eva774 approved these changes

2021-01-17 20:03 UTC, Autom3 approved these changes

2021-01-17 21:42 UTC, Jan-PieterBaert commented on Commands/notify.py
> +            await ctx.send(users_str)
To solve #96 you could run rstrip on the `users_str` to cut of the `, ` or you could slice those 2 chars away

2021-01-18 14:27 UTC, woutermeuwis approved these changes

2021-01-18 14:27 UTC, merged